export default {
  THEME_CHANGE: "THEME_CHANGE",
  THEME_INIT: "THEME_INIT",
  POP_REFRESH:'POP_REFRESH',
  POP_REFRESH_FAIL:'POP_REFRESH_FAIL',
  POP_REFRESH_SUCCESS:'POP_REFRESH_SUCCESS',
  POP_LOAD_MORE_SUCCESS: "POP_LOAD_MORE_SUCCESS",
  POP_LOAD_MORE_FAIL: "POP_LOAD_MORE_FAIL"

}